### ISSUE TITLE
macOS sounddevice.PortAudioError

### ISSUE THREAD

**Issue by mattbk** [w9cf/cwsim#3]
Thanks for the work!

Trying to run this on macOS Ventura with a new Python install. Ran through the installation and the main window shows up, but pushing "Start" crashes it and gives this feedback:
```
$ python3 python/cwsim.py
||PaMacCore (AUHAL)|| Error on line 1316: err='-66748', msg=Unknown Error
Traceback (most recent call last):
  File "/Users/Matt/Desktop/cwsim/cwsim/python/cwsim.py", line 554, in startStop
    self.contest.start()
  File "/Users/Matt/Desktop/cwsim/cwsim/python/contest.py", line 333, in start
    self.stream = sd.OutputStream(samplerate=self._rate
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Matt/Library/Python/3.12/lib/python/site-packages/sounddevice.py", line 1494, in __init__
    _StreamBase.__init__(self, kind='output', wrap_callback='array',
  File "/Users/Matt/Library/Python/3.12/lib/python/site-packages/sounddevice.py", line 898, in __init__
    _check(_lib.Pa_OpenStream(self._ptr, iparameters, oparameters,
  File "/Users/Matt/Library/Python/3.12/lib/python/site-packages/sounddevice.py", line 2747, in _check
    raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Error opening OutputStream: Internal PortAudio error [PaErrorCode -9986]
Abort trap: 6
```

**Comment by w9cf** [comment]
Please run
```
python -m sounddevice
```
which should show the available sound devices. This may give a clue where to start.

**Comment by mattbk** [comment]
I should have added that I'm on an M2 machine in case that matters.
```
$ python3 -m sounddevice
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/Matt/Library/Python/3.12/lib/python/site-packages/sounddevice.py", line 58, in <module>
    from _sounddevice import ffi as _ffi
  File "/Users/Matt/Library/Python/3.12/lib/python/site-packages/_sounddevice.py", line 2, in <module>
    import _cffi_backend
ImportError: dlopen(/Users/Matt/Library/Python/3.12/lib/python/site-packages/_cffi_backend.cpython-312-darwin.so, 0x0002): tried: '/Users/Matt/Library/Python/3.12/lib/python/site-packages/_cffi_backend.cpython-312-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/Matt/Library/Python/3.12/lib/python/site-packages/_cffi_backend.cpython-312-darwin.so' (no such file), '/Users/Matt/Library/Python/3.12/lib/python/site-packages/_cffi_backend.cpython-312-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

**Comment by w9cf** [comment]
It seems to me that the error:
```
mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')
```
indicates that your version of cffi is for an intel architecture instead of the arm architecture. I am
not very familiar with Macs, but you could first try to see if you can install from source with:
```
pip install cffi --no-binary :all:
```

Alternatively you  could first try downloading an arm cffi wheel from pypi and try installing it. I went
to https://pypi.org/project/cffi/#files and this wheel seems to be for python 3.12 with arm support:
```
https://files.pythonhosted.org/packages/b4/f6/b28d2bfb5fca9e8f9afc9d05eae245bed9f6ba5c2897fefee7a9abeaf091/cffi-1.16.0-cp312-cp312-macosx_11_0_arm64.whl
```

Then run
```
pip install cffi-1.16.0-cp312-cp312-macosx_11_0_arm64.whl 
```

If that doesn't work you will likely need to build cffi from source in another way or wait for the correct wheel to be built by
someone else.

**Comment by mattbk** [comment]
```
$ pip3 install cffi --no-binary :all:
Requirement already satisfied: cffi in ./Library/Python/3.12/lib/python/site-packages (1.16.0)
Requirement already satisfied: pycparser in ./Library/Python/3.12/lib/python/site-packages (from cffi) (2.21)
```
I tried the wheel and got the same thing, but it suggested `--force-reinstall`. When I ran that I got some xcode errors.
```
$ pip3 install cffi --force-reinstall --no-binary :all:
Collecting cffi
  Downloading cffi-1.16.0.tar.gz (512 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 512.9/512.9 kB 898.5 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pycparser (from cffi)
  Downloading pycparser-2.21.tar.gz (170 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.9/170.9 kB 1.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: cffi, pycparser
  Building wheel for cffi (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for cffi (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [65 lines of output]
      xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
      xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
```
which led me to https://stackoverflow.com/a/52522566/2152245. I am running `xcode-select --install` which told me I needed to install the command line developer tools. I'm in the middle of that and will update.

**Comment by mattbk** [comment]
This may be an issue unique to my system. Closing for now until I figure it out.

**Comment by mattbk** [comment]
Although I upgraded the OS and installed Python fresh, it still had packages from the old architecture. Following the error messages and a series of `pip3 install --force-reinstall <package>` commands finally got things working. Sorry for the trouble!
